apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  replicas:
    min: 2
    max: 3
  prometheus:
    enabled: true
    path: /internal/prometheus
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 300Mi
      cpu: 50m
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad
        - application: familie-ks-soknad
    outbound:
      rules:
        - application: familie-baks-mottak
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: kodeverk.prod-fss-pub.nais.io
        - host: api-gw.oera.no
        - host: login.microsoftonline.com
  vault:
    enabled: false
  env:
    - name: APP_TEAM
      value: teamfamilie
    - name: SPRING_PROFILES_ACTIVE
      value: prod
