apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-baks-soknad-api
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 30
    failureThreshold: 10
  replicas:
    min: 2
    max: 2
  prometheus:
    enabled: true
    path: /internal/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  resources:
    limits:
      memory: 500Mi
    requests:
      memory: 300Mi
      cpu: 10m
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-soknad
        - application: familie-ks-soknad
    outbound:
      rules:
        - application: familie-baks-mottak
        - application: sokos-kontoregister-person
          namespace: okonomi
        - application: logging
          namespace: nais-system
      external:
        - host: api-gw-q1.oera.no
        - host: login.microsoftonline.com
        - host: pdl-api.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no
  vault:
    enabled: false
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: APP_TEAM
      value: teamfamilie
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
