FAMILIE_BA_MOTTAK_URL: https://familie-ba-mottak.prod-fss-pub.nais.io
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_AUDIENCE: prod-fss:pdl:pdl-api
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
KODEVERK_URL: https://kodeverk.prod-fss-pub.nais.io

no.nav.security.jwt:
  client:
    registration:
      mottak-clientcredentials:
        token-exchange:
          audience: prod-fss:teamfamilie:familie-ba-mottak

logging.level.no.nav.security: INFO
