FAMILIE_BAKS_MOTTAK_URL: http://localhost:8090
PDL_URL: http://localhost:1337/rest/api/pdl
PDL_SCOPE: api://dev-fss.pdl.pdl-api-q1/.default
PDL_TOKENX_SCOPE: dev-fss:pdl:pdl-api-q1
KODEVERK_URL: #Mockes lokalt
KODEVERK_SCOPE: dummy
KONTOREGISTER_URL: http://sokos-kontoregister-person.okonomi/api/borger/v1
KONTOREGISTER_SCOPE: dummy
MOTTAK_SCOPE: dummy

NAIS_TOKEN_ENDPOINT: http://localhost
NAIS_TOKEN_EXCHANGE_ENDPOINT: http://localhost

TOKEN_X_WELL_KNOWN_URL: https://fakedings.intern.dev.nav.no/fake/.well-known/openid-configuration
TOKEN_X_ISSUER: https://fakedings.intern.dev.nav.no/fake
TOKEN_X_CLIENT_ID: dev-gcp:teamfamilie:familie-baks-soknad-api
TOKEN_X_JWKS_URI: https://fakedings.intern.dev.nav.no/fake/jwks
