FAMILIE_BAKS_MOTTAK_URL: http://familie-baks-mottak
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
PDL_TOKENX_SCOPE: prod-fss:pdl:pdl-api
KODEVERK_URL: https://kodeverk-api.nav.no
KODEVERK_SCOPE: api://prod-gcp.team-rocket.kodeverk-api/.default
KONTOREGISTER_URL: http://sokos-kontoregister-person.okonomi/api/borger/v1
KONTOREGISTER_SCOPE: prod-gcp:okonomi:sokos-kontoregister-person
MOTTAK_SCOPE: prod-gcp:teamfamilie:familie-baks-mottak

logging.level.no.nav.security: INFO
