FAMILIE_BAKS_MOTTAK_URL: http://familie-baks-mottak
PDL_URL: https://pdl-api.prod-fss-pub.nais.io
PDL_AUDIENCE: prod-fss:pdl:pdl-api
PDL_SCOPE: api://prod-fss.pdl.pdl-api/.default
KODEVERK_URL: https://kodeverk-api.nav.no
KODEVERK_SCOPE: api://prod-gcp.team-rocket.kodeverk-api/.default
KONTOREGISTER_URL: http://sokos-kontoregister-person.okonomi/api/borger/v1

no.nav.security.jwt:
  client:
    registration:
      mottak-clientcredentials:
        token-exchange:
          audience: prod-gcp:teamfamilie:familie-baks-mottak
      kontoregister-clientcredentials:
        token-exchange:
          audience: prod-gcp:okonomi:sokos-kontoregister-person

logging.level.no.nav.security: INFO
