application.name: familie-ba-soknad-api

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true

FAMILIE_BA_MOTTAK_URL: dummy
PDL_URL: dummy
KODEVERK_URL: dummy

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookie_name: selvbetjening-idtoken
  client:
    registration:
      mottak-clientcredentials:
        resource-url: ${FAMILIE_BA_MOTTAK_URL}
        well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-auth-method: private_key_jwt
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
      pdl:
        resource-url: ${PDL_URL}
        well-known-url: ${TOKEN_X_WELL_KNOWN_URL}
        grant-type: urn:ietf:params:oauth:grant-type:token-exchange
        token-exchange:
          audience: ${PDL_AUDIENCE}
        authentication:
          client-id: ${TOKEN_X_CLIENT_ID}
          client-auth-method: private_key_jwt
          client-jwk: ${TOKEN_X_PRIVATE_JWK}
      pdl-clientcredentials:
        resource-url: ${PDL_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${PDL_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

logging.level.no.nav.security: DEBUG
