application.name: familie-baks-soknad-api

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration
  main.banner-mode: "off"
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: false

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true

FAMILIE_BAKS_MOTTAK_URL: dummy
PDL_URL: dummy
KODEVERK_URL: dummy
KODEVERK_SCOPE: "dummy-scope"
PDL_SCOPE: "dummy-scope"
PDL_TOKENX_SCOPE: "dummy-scope"
MOTTAK_SCOPE: "dummy-scope"
KONTOREGISTER_SCOPE: "dummy-scope"

TOKEN_X_ISSUER: dummy
TOKEN_X_CLIENT_ID: dummy
TOKEN_X_JWKS_URI: dummy

logging.level.no.nav.security: DEBUG
