name: Build-Deploy-Preprod
on:
  workflow_dispatch:
  push:
    branches-ignore:
      # build-deploy-prod deployer allerede til dev, dette førte til en race condition som stopper deploy til prod
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy-to-dev:
    name: Bygg app/image, push til github, deploy til dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-cache-${{ hashFiles('pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-cache-
      - name: Bygg med maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --no-transfer-progress package --settings .m2/maven-settings.xml --file pom.xml

      - uses: nais/docker-build-push@v0
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        id: docker-push
        with:
          team: teamfamilie
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/classes/META-INF/sbom/application.cdx.json

      - name: Deploy til dev-gcp
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: dev-gcp-teamfamilie.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
