name: Test trivy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    permissions:
      contents: write # to write sarif
      security-events: write # push sarif to github security
      id-token: write # nais/login
    uses: navikt/familie-baks-gha-workflows/.github/workflows/scan-vulnerabilities-maven.yaml@scan-vulnerabilities
    secrets: inherit

