name: Test trivy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    permissions:
      contents: read
      id-token: write
    uses: navikt/familie-baks-gha-workflows/.github/workflows/build-maven-app.yaml@main
    with:
      skip-tests: ${{ inputs.skip-tests }}
      build-image: true
      push-image: true
    secrets: inherit
  trivy:
    name: Trivy
    permissions:
      contents: write
      security-events: write
      id-token: write
    needs: [ build ]
    uses: navikt/familie-baks-gha-workflows/.github/workflows/trivy.yaml@main
    with:
      image: ${{ needs.build.outputs.image }}
