# Trenger en workflow som ikke er i bruk for testing og utvikling av workflow templates i egen branch.
# Skriver man om en eksisterende workflow i egen branch blir det veldig forvirrende i grensesnittet til GitHub for de som ikke er i loopen.
name: Test workflow
on:
  workflow_dispatch:
jobs:
  test-workflow:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          echo "This is a workflow"
  varsle-slack:
    name: Slack-melding ved feil
    permissions: {}
    uses: navikt/familie-baks-gha-workflows/.github/workflows/notify-failed-workflow.yaml@slack-varsling # ratchet:exclude
    secrets:
      BAKS_DEPLOYMENTS_SLACK_WEBHOOK: ${{ secrets.BAKS_DEPLOYMENTS_SLACK_WEBHOOK }}
  notify-audit:
    name: Slack-melding hvis ikke main branch
    permissions: {}
    uses: navikt/familie-baks-gha-workflows/.github/workflows/notify-audited-deploy.yaml@slack-varsling # ratchet:exclude
    secrets:
      BAKS_AUDIT_ALERTS_SLACK_WEBHOOK: ${{ secrets.BAKS_AUDIT_ALERTS_SLACK_WEBHOOK }}
